# Generated by Django 4.0.6 on 2022-08-09 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myfarm_app', '0002_person_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='image',
            new_name='test_image',
        ),
    ]
