# Generated by Django 4.0.6 on 2022-08-09 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myfarm_app', '0003_rename_image_person_test_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='test_image',
            field=models.ImageField(default='/images/default_image.jpeg', upload_to=''),
        ),
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Myfarm_app.person')),
            ],
        ),
    ]
