# Generated by Django 4.0.6 on 2022-08-09 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myfarm_app', '0004_alter_person_test_image_productimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImg',
        ),
    ]
