# Generated by Django 4.0.6 on 2022-08-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myfarm_app', '0005_delete_productimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='test_image',
            field=models.ImageField(upload_to='images', verbose_name='image'),
        ),
    ]
