# Generated by Django 4.0.6 on 2022-08-10 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myfarm_app', '0006_alter_person_test_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
