# Generated by Django 4.0.6 on 2022-08-10 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myfarm_app', '0007_alter_person_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='test_image',
            new_name='image',
        ),
    ]
